# Generated by Django 4.0.4 on 2022-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fields_fieldlist_apiendpoint_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldlist',
            name='field_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
