# Generated by Django 4.0.4 on 2022-04-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fieldlist_field_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('validate_value', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fieldlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
